FROM golang:1.21
#Criação do diretorio 
WORKDIR /app 
#Copia main.go e dados.json para o contêiner
COPY main.go .
#COPY dados.json .
# Compila o servidor
RUN go build -o server main.go
# expõe a porta 8080 para conexões TCP
EXPOSE 8080
#Quando o contêiner inicia, executa ./server para rodar o servidor
RUN go build -o server main.go
CMD ["./server"]
