FROM golang:1.21
#Criação do diretorio 
WORKDIR /app 
#Copia server.go para o contêiner
COPY server.go .

RUN ln -s /Projeto-Inicial-Pbl-Redes/dados/dadosVeiculos.json ./dadosVeiculos.json
RUN ln -s /Projeto-Inicial-Pbl-Redes/dados/dadosPontos.json ./dadosPontos.json

# Compila o servidor
RUN go build -o server server.go
# expõe a porta 8080 para conexões TCP
EXPOSE 8080
#Quando o contêiner inicia, executa ./server para rodar o servidor
RUN go build -o server server.go
CMD ["./server"]
