FROM golang:1.20
WORKDIR /app
COPY ponto.go .
RUN ln -s /Projeto-Inicial-Pbl-Redes/dados/MapaDeFeira.csv ./MapaDeFeira.csv
RUN ln -s /Projeto-Inicial-Pbl-Redes/dados/dadosVeiculos.json ./dadosVeiculos.json
RUN go build -o ponto ponto.go
CMD ["./ponto"]
